name: Node.js CI

on:
  push:
    branches: [ "karsajobs-ui" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: Dockerfile

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/f00ds/karsajobs-ui:latest
        docker push ghcr.io/f00ds/karsajobs-ui:latest