name: Shipping Service

on:
  push:
    branches: [ "shipping-service" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
          npm install

  containerized:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: Dockerfile

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/f00ds/shipping-service:latest
